{
 "title": "Qdrant Operator V2 Dashboard",
 "description": "An overview of all qdrant operator instances",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Operator Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Operator Status Over Time",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{deployment=\"qdrant-operator-v2\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Operator Versions",
   "type": "table",
   "gridPos": { "h": 4, "w": 9, "x": 13, "y": 1 },
   "targets": [
    {
     "expr": "group(kube_pod_container_info{container=\"operator\", pod=~\"qdrant-operator-v2-.*\"}) by(namespace,image)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Manager Versions",
   "type": "table",
   "gridPos": { "h": 4, "w": 9, "x": 13, "y": 5 },
   "targets": [
    {
     "expr": "group(kube_pod_container_info{container=\"qdrant-cluster-manager\", pod=~\"qdrant-cluster-manager-.*\"}) by(kubernetes_cluster,image)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Operator Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "CPU usage by Qdrant operator instances across all managed cloud regions",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{container=\"operator\", pod=~\"qdrant-operator-v2-.*\"}[5m]) * 100",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Memory usage by Qdrant operator instances across all managed cloud regions",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{pod=~\"qdrant-operator-v2-.*\", container=\"operator\"}",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  { "title": "Reconciliation Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Active Worker Per Controller",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(controller_runtime_active_workers{pod=~\"qdrant-operator-v2-.*\"}) by (controller,namespace)",
     "legendFormat": "{{controller}} ({{namespace}})"
    }
   ]
  },
  {
   "title": "Max Concurrent Workers",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "max(controller_runtime_max_concurrent_reconciles{pod=~\"qdrant-operator-v2-.*\"}) by(controller)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reconciliation Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{pod=~\"qdrant-operator-v2-.*\"}[5m])) by(namespace,controller)",
     "legendFormat": "{{controller}} ({{namespace}})"
    }
   ]
  },
  {
   "title": "Reconciliation Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_errors_total{pod=~\"qdrant-operator-v2-.*\"}[5m])) by(namespace,controller)",
     "legendFormat": "{{controller}} ({{namespace}})"
    }
   ]
  },
  { "title": "Workqueue Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Workqueue Length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "workqueue_depth{pod=~\"qdrant-operator-v2-.*\"}",
     "legendFormat": "{{name}} ({{namespace}})"
    }
   ]
  },
  {
   "title": "Workqueue Add Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total{pod=~\"qdrant-operator-v2-.*\"}[5m])) by (namespace, name)",
     "legendFormat": "{{name}} ({{namespace}})"
    }
   ]
  },
  {
   "title": "Workqueue Retries Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(workqueue_retries_total{pod=~\"qdrant-operator-v2-.*\"}[5m])) by (namespace, name)",
     "legendFormat": "{{name}} ({{namespace}})"
    }
   ]
  },
  {
   "title": "Unfinished Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(workqueue_unfinished_work_seconds{pod=~\"qdrant-operator-v2-.*\"}[5m])",
     "legendFormat": "{{name}} ({{namespace}})"
    }
   ]
  },
  {
   "title": "Seconds For Items Stay In Queue (before being requested) (P90)",
   "type": "timeseries",
   "description": "How long in seconds an item stays in workqueue before being requested",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(workqueue_queue_duration_seconds_bucket{pod=~\"qdrant-operator-v2-.*\"}[5m])) by (namespace, pod, name, le))",
     "legendFormat": "{{name}} ({{namespace}})"
    }
   ]
  },
  {
   "title": "Seconds For Items Stay In Queue (before being requested) (P99)",
   "type": "timeseries",
   "description": "How long in seconds an item stays in workqueue before being requested",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(workqueue_queue_duration_seconds_bucket{pod=~\"qdrant-operator-v2-.*\"}[5m])) by (namespace, pod, name, le))",
     "legendFormat": "{{name}} ({{namespace}})"
    }
   ]
  },
  {
   "title": "Seconds Processing Items From WorkQueue (P90)",
   "type": "timeseries",
   "description": "How long in seconds processing an item from workqueue takes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(workqueue_work_duration_seconds_bucket{pod=~\"qdrant-operator-v2-.*\"}[5m])) by (namespace, pod, name, le))",
     "legendFormat": "{{name}} ({{namespace}})"
    }
   ]
  },
  {
   "title": "Seconds Processing Items From WorkQueue (P99)",
   "type": "timeseries",
   "description": "How long in seconds processing an item from workqueue takes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(workqueue_work_duration_seconds_bucket{pod=~\"qdrant-operator-v2-.*\"}[5m])) by (namespace, pod, name, le))",
     "legendFormat": "{{name}} ({{namespace}})"
    }
   ]
  },
  { "title": "REST Request Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Rest Client Requests Rate (by instance)",
   "type": "timeseries",
   "description": "Number of HTTP requests",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{pod=~\"qdrant-operator-v2-.*\"}[5m])) by (namespace,pod)",
     "legendFormat": "{{namespace}} ({{pod}})"
    }
   ]
  },
  {
   "title": "Rest Client Requests Rate (by method)",
   "type": "timeseries",
   "description": "Number of HTTP requests categorized by HTTP method",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{pod=~\"qdrant-operator-v2-.*\"}[5m])) by (namespace,method)",
     "legendFormat": "{{method}} ({{namespace}})"
    }
   ]
  },
  { "title": "Cluster Manager Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "Cluster manager call duration (P90)",
   "type": "timeseries",
   "description": "Time taken by the cluster-manager to process a call in seconds",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(qdrant_operator_cluster_manager_call_duration_seconds_bucket{pod=~\"qdrant-operator-v2-.*\"}[5m])) by (namespace, pod, le))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Cluster manager call duration (P99)",
   "type": "timeseries",
   "description": "Time taken by the cluster-manager to process a call in seconds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(qdrant_operator_cluster_manager_call_duration_seconds_bucket{pod=~\"qdrant-operator-v2-.*\"}[5m])) by (namespace, pod, le))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "CPU usage by cluster-manager instances across all managed cloud regions",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{pod=~\"qdrant-cluster-manager-.*\", container=\"qdrant-cluster-manager\"}[5m]) * 100",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Memory usage by Qdrant operator instances across all managed cloud regions",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{pod=~\"qdrant-cluster-manager-.*\", container=\"qdrant-cluster-manager\"}",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  }
 ]
}