{
 "title": "Qdrant Cloud Public Dashboard",
 "description": "Grafana dashboard for Qdrant clusters deployed on Qdrant Cloud Platform.",
 "tags": [ "qdrant" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster_id",
    "label": "Cluster ID",
    "query": {
     "query": "label_values(qdrant_operator_cluster_info_total,cluster_id)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{pod=~\"qdrant-$cluster_id-.*\"},pod)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(kube_pod_container_info{container!=\"kubectl\"},container)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{pod=~\"$pod\"},namespace)"
    }
   },
   {
    "name": "envoy_cluster",
    "query": {
     "query": "label_values(envoy_cluster_upstream_rq_total{envoy_cluster_name=~\"$cluster_id-.+\"},envoy_cluster_name)"
    }
   },
   {
    "name": "pvc_storage",
    "query": {
     "query": "label_values(kube_persistentvolumeclaim_info{namespace=~\"$namespace\", persistentvolumeclaim=~\"qdrant-storage-qdrant-$cluster_id-.*\"},persistentvolumeclaim)"
    }
   },
   {
    "name": "pvc_snapshots",
    "query": {
     "query": "label_values(kube_persistentvolumeclaim_info{namespace=~\"$namespace\", persistentvolumeclaim=~\"qdrant-snapshots-qdrant-$cluster_id-.*\"},persistentvolumeclaim)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "panels": [
    {
     "title": "Version",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "qdrant_operator_cluster_info_total{cluster_id=\"$cluster_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of Nodes",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "qdrant_operator_cluster_info_total{cluster_id=\"$cluster_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Num of Available Nodes",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "qdrant_operator_cluster_status_nodes_ready{cluster_id=\"$cluster_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Package Type",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "qdrant_operator_cluster_info_total{cluster_id=\"$cluster_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Per Node",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "qdrant_operator_cluster_info_total{cluster_id=\"$cluster_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Per Node",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "qdrant_operator_cluster_info_total{cluster_id=\"$cluster_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Storage Per Node",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "qdrant_operator_cluster_info_total{cluster_id=\"$cluster_id\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Status",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "qdrant_operator_cluster_phase{cluster_id=\"$cluster_id\"} == 1",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of Collections",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "qdrant_collection_number_of_collections{pod=~\"$pod\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Usage Percentage",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 6, "x": 3, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(rate(container_cpu_usage_seconds_total{pod=~\"qdrant-$cluster_id-.*\", container=\"qdrant\"}[2m])) by (pod) / max(kube_pod_container_resource_limits{pod=~\"qdrant-$cluster_id-.*\", unit=\"core\"}) by (pod) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Usage Percentage",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 6, "x": 9, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(qdrant_node_rssanon_bytes{pod=~\"qdrant-$cluster_id-.*\"}) by (pod) /max(kube_pod_container_resource_limits{pod=~\"qdrant-$cluster_id-.*\", unit=\"byte\"}) by (pod) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Storage Usage Percentage",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 6, "x": 15, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"$pvc_storage\",namespace=~\"$namespace\"} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"$pvc_storage\",namespace=~\"$namespace\"}) * 100",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Average Response Time",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 21, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(envoy_cluster_upstream_rq_time_sum{envoy_cluster_name=~\"$cluster_id-.+\"}) / sum(envoy_cluster_upstream_rq_time_count{envoy_cluster_name=~\"$cluster_id-.+\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Backup Scheduled",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(qdrant_operator_cluster_scheduled_snapshot_info_total{cluster_id=~\"$cluster_id\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Collections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Collection Configuration",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "max(qdrant_collection_config_params_on_disk_payload{pod=~\"qdrant-$cluster_id-.*\"}) by(collection)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(qdrant_collection_config_params_read_fanout_factor{pod=~\"qdrant-$cluster_id-.*\"}) by(collection)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(qdrant_collection_config_params_replication_factor{pod=~\"qdrant-$cluster_id-.*\"}) by(collection)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(qdrant_collection_config_params_write_consistency_factor{pod=~\"qdrant-$cluster_id-.*\"}) by(collection)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(qdrant_collection_config_wal_capacity_mb{pod=~\"qdrant-$cluster_id-.*\"}) by(collection)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(qdrant_collection_config_wal_segments_ahead{pod=~\"qdrant-$cluster_id-.*\"}) by(collection)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(qdrant_collection_config_params_vector_size{pod=~\"qdrant-$cluster_id-.*\"}) by(collection,distance,mode,ondisk)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(qdrant_collection_config_params_shard_number{pod=~\"qdrant-$cluster_id-.*\"}) by(collection)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HNSW Configuration",
     "type": "table",
     "gridPos": { "h": 8, "w": 13, "x": 0, "y": 98 },
     "targets": [
      {
       "expr": "max(qdrant_collection_config_hnsw_full_ef_construct{pod=~\"qdrant-$cluster_id-.*\"}) by(collection)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(qdrant_collection_config_hnsw_full_scan_threshold{pod=~\"qdrant-$cluster_id-.*\"}) by(collection)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(qdrant_collection_config_hnsw_m{pod=~\"qdrant-$cluster_id-.*\"}) by(collection)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(qdrant_collection_config_hnsw_max_indexing_threads{pod=~\"qdrant-$cluster_id-.*\"}) by(collection)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(qdrant_collection_config_hnsw_on_disk{pod=~\"qdrant-$cluster_id-.*\"}) by(collection)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(qdrant_collection_config_hnsw_payload_m{pod=~\"qdrant-$cluster_id-.*\"}) by(collection)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Quantization",
     "type": "table",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 98 },
     "targets": [
      {
       "expr": "max(qdrant_collection_config_quantization_always_ram{pod=~\"qdrant-$cluster_id-.*\"}) by(collection, quantization_type)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(qdrant_collection_config_quantization_product_compression{pod=~\"qdrant-$cluster_id-.*\"}) by(collection)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(qdrant_collection_config_quantization_scalar_quantile{pod=~\"qdrant-$cluster_id-.*\"}) by(collection)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(qdrant_collection_config_quantization_scalar_type{pod=~\"qdrant-$cluster_id-.*\"}) by(collection,type)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Optimizer Configuration",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 106 },
     "targets": [
      {
       "expr": "max(qdrant_collection_config_optimizer_default_segment_number{pod=~\"qdrant-$cluster_id-.*\"}) by(collection)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(qdrant_collection_config_optimizer_flush_interval_sec{pod=~\"qdrant-$cluster_id-.*\"}) by(collection)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(qdrant_collection_config_optimizer_indexing_threshold{pod=~\"qdrant-$cluster_id-.*\"}) by(collection)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(qdrant_collection_config_optimizer_max_optimization_threads{pod=~\"qdrant-$cluster_id-.*\"}) by(collection)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(qdrant_collection_config_optimizer_max_segment_size{pod=~\"qdrant-$cluster_id-.*\"}) by(collection)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(qdrant_collection_config_optimizer_memmap_threshold{pod=~\"qdrant-$cluster_id-.*\"}) by(collection)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(qdrant_collection_config_optimizer_vacuum_min_vector_number{pod=~\"qdrant-$cluster_id-.*\"}) by(collection)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nodes",
     "type": "table",
     "gridPos": { "h": 8, "w": 14, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "max(qdrant_collection_role{pod=~\"qdrant-$cluster_id-.*\"}) by(pod)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(qdrant_collection_is_voter{pod=~\"qdrant-$cluster_id-.*\"}) by(pod)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(qdrant_collection_consensus_thread_status{pod=~\"qdrant-$cluster_id-.*\"}) by(pod)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(qdrant_collection_term{pod=~\"qdrant-$cluster_id-.*\"}) by(pod)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(qdrant_collection_commit{pod=~\"qdrant-$cluster_id-.*\"}) by(pod)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(qdrant_collection_pending_operations{pod=~\"qdrant-$cluster_id-.*\"}) by(pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Shards, Vectors, Points (per Nodes)",
     "type": "table",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 3 },
     "targets": [
      {
       "expr": "count(group(qdrant_collection_shard_segment_type{pod=~\"qdrant-$cluster_id-.*\"}) by(pod,collection,shard_id))by(pod)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(qdrant_collection_shard_segment_num_vectors{pod=~\"qdrant-$cluster_id-.*\"}) by(pod)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(qdrant_collection_shard_segment_num_indexed_vectors{pod=~\"qdrant-$cluster_id-.*\"}) by(pod)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(qdrant_collection_shard_segment_num_points{pod=~\"qdrant-$cluster_id-.*\"}) by(pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Node Status Over Time",
     "type": "state-timeline",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(pod) (kube_pod_status_phase{phase=\"Running\", pod=~\"qdrant-$cluster_id-.*\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Shards Distribution",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 108 },
     "targets": [
      {
       "expr": "group(qdrant_collection_shard_segment_type{pod=~\"qdrant-$cluster_id-.*\"}) by(collection,pod,shard_id)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Node Restarts Over Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (pod,container) (ceil(delta(kube_pod_container_status_restarts_total{pod=~\"$pod\",namespace=~\"$namespace\"}[$__range])))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Last observed node termination reason",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 119 },
     "targets": [
      {
       "expr": "sum by (pod,container,reason) (kube_pod_container_status_last_terminated_reason{pod=~\"$pod\",namespace=~\"$namespace\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Backups",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Schedules",
     "type": "table",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "count(qdrant_operator_cluster_scheduled_snapshot_info_total{cluster_id=~\"$cluster_id\"}) by(name,schedule,retention)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Snapshots",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 9, "y": 4 },
     "targets": [
      {
       "expr": "count(qdrant_operator_cluster_snapshot_phase{cluster_id=~\"$cluster_id\"} == 1) by(name,phase)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage: Absolute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (pod,container) (rate(container_cpu_usage_seconds_total{pod=~\"$pod\",container=~\"$container\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "min (kube_pod_container_resource_requests{namespace=~\"$namespace\", pod=~\"$pod\", container=\"$container\", unit=\"core\"})",
       "legendFormat": "Request"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{namespace=~\"$namespace\", pod=~\"$pod\", container=\"$container\", unit=\"core\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "CPU usage: Relative to limit",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod=~\"$pod\", container=\"$container\"}[$__rate_interval])) by (pod,container) / avg(kube_pod_container_resource_requests{namespace=~\"$namespace\", pod=~\"$pod\", container=\"$container\", resource=\"cpu\", unit=\"core\"}) by (pod,container)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", resource=\"cpu\", unit=\"core\"}/kube_pod_container_resource_requests{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", resource=\"cpu\", unit=\"core\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "CPU: Throttling",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[$__rate_interval])) by (pod,container) /sum(increase(container_cpu_cfs_periods_total{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[$__rate_interval])) by (pod,container)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Memory usage: Absolute (working set)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (pod,container) (container_memory_working_set_bytes{pod=~\"$pod\",container=~\"$container\"})",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{pod=~\"$pod\",container=~\"$container\",unit=\"byte\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Memory usage: Relative to limit (working set)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max by (pod,container) (container_memory_working_set_bytes{namespace=~\"$namespace\", pod=~\"$pod\", container=\"$container\"}) / max by (pod,container) (kube_pod_container_resource_requests{namespace=~\"$namespace\", pod=~\"$pod\", container=\"$container\",resource=\"memory\",unit=\"byte\"})",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", unit=\"byte\",resource=\"memory\"}/kube_pod_container_resource_requests{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\", unit=\"byte\",resource=\"memory\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Memory: RSS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (pod,container) (container_memory_rss{pod=~\"$pod\",container=~\"$container\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Memory usage: Absolute (RSSAnon)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 109 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (pod) (qdrant_node_rssanon_bytes{pod=~\"$pod\"})",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{pod=~\"$pod\",container=\"qdrant\",unit=\"byte\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Memory usage: Relative to request (RSSAnon)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 109 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max by (pod) (qdrant_node_rssanon_bytes{namespace=~\"$namespace\", pod=~\"$pod\"}) / max by (pod) (kube_pod_container_resource_requests{namespace=~\"$namespace\", pod=~\"$pod\", container=\"qdrant\",resource=\"memory\",unit=\"byte\"})",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{namespace=~\"$namespace\", pod=~\"$pod\", container=\"qdrant\", unit=\"byte\",resource=\"memory\"}/kube_pod_container_resource_requests{namespace=~\"$namespace\", pod=~\"$pod\", container=\"qdrant\", unit=\"byte\",resource=\"memory\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Memory: Size of memory mapped files (mmap)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 109 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (pod,container) (container_memory_mapped_file{pod=~\"$pod\",container=~\"$container\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Memory: Page cache",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (pod,container) (container_memory_cache{pod=~\"$pod\",container=~\"$container\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "IOPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum by (pod,container,device) (irate(container_fs_writes_total{pod=~\"$pod\",namespace=~\"$namespace\",container=~\"$container\"}[2m])+rate(container_fs_reads_total{pod=~\"$pod\",namespace=~\"$namespace\",container=~\"$container\"}[2m]))",
       "legendFormat": "{{pod}}:{{device}}"
      }
     ]
    },
    {
     "title": "IO Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{id!=\"/\",pod=~\"qdrant-$cluster_id-.*\"}[2m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Data Disk: Absolute usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 125 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"$pvc_storage\",namespace=~\"$namespace\"}",
       "legendFormat": "{{persistentvolumeclaim}}"
      },
      {
       "expr": "min(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"$pvc_storage\",namespace=~\"$namespace\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Data Disk: Usage relative to limit",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 125 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"$pvc_storage\",namespace=~\"$namespace\"}/kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"$pvc_storage\",namespace=~\"$namespace\"}",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Data Disk: Inode usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 125 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "kubelet_volume_stats_inodes_used{persistentvolumeclaim=~\"$pvc_storage\",namespace=~\"$namespace\"}",
       "legendFormat": "{{persistentvolumeclaim}}"
      },
      {
       "expr": "min(kubelet_volume_stats_inodes{persistentvolumeclaim=~\"$pvc_storage\",namespace=~\"$namespace\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Snapshot Disk: Absolute usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 133 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"$pvc_snapshots\",namespace=~\"$namespace\"}",
       "legendFormat": "{{persistentvolumeclaim}}"
      },
      {
       "expr": "min(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"$pvc_snapshots\",namespace=~\"$namespace\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Snapshot Disk: Usage relative to limit",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 133 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"$pvc_snapshots\",namespace=~\"$namespace\"}/kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"$pvc_snapshots\",namespace=~\"$namespace\"}",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Snapshot Disk: Inode usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 133 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "kubelet_volume_stats_inodes_used{persistentvolumeclaim=~\"$pvc_snapshots\",namespace=~\"$namespace\"}",
       "legendFormat": "{{persistentvolumeclaim}}"
      },
      {
       "expr": "min(kubelet_volume_stats_inodes{persistentvolumeclaim=~\"$pvc_snapshots\",namespace=~\"$namespace\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "File descriptors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 141 },
     "targets": [
      {
       "expr": "sum by (pod,container) (container_file_descriptors{pod=~\"$pod\",namespace=~\"$namespace\",container=~\"$container\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Disk: Read",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 141 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (pod,container,device) (rate(container_fs_reads_bytes_total{pod=~\"$pod\",namespace=~\"$namespace\",container=~\"$container\"}[2m]))",
       "legendFormat": "{{pod}}:{{device}}"
      }
     ]
    },
    {
     "title": "Disk: Write",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 141 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (pod,container,device) (rate(container_fs_writes_bytes_total{pod=~\"$pod\",namespace=~\"$namespace\",container=~\"$container\"}[2m]))",
       "legendFormat": "{{pod}}:{{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request latency (p50/p95/p99)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (le, envoy_cluster_name) (rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=~\"$envoy_cluster\"}[$__rate_interval])))",
       "legendFormat": "p50 {{envoy_cluster_name}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le, envoy_cluster_name) (rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=~\"$envoy_cluster\"}[$__rate_interval])))",
       "legendFormat": "p95 {{envoy_cluster_name}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le, envoy_cluster_name) (rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=~\"$envoy_cluster\"}[$__rate_interval])))",
       "legendFormat": "p99 {{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (envoy_cluster_name) (rate(envoy_cluster_upstream_rq_total{envoy_cluster_name=~\"$envoy_cluster\"}[$__rate_interval]))",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Response Codes (by Class)",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(envoy_cluster_upstream_rq_xx{envoy_cluster_name=~\"$cluster_id-.+\"}[12h])) by (envoy_response_code_class)",
       "legendFormat": "{{envoy_response_code_class}}xx"
      }
     ]
    },
    {
     "title": "Open Connections Over Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(envoy_cluster_upstream_cx_active{envoy_cluster_name=~\"$envoy_cluster\"}) by (envoy_cluster_name)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Ingress",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(envoy_cluster_upstream_cx_tx_bytes_total{envoy_cluster_name=~\"$envoy_cluster\"}[$__rate_interval])) by (envoy_cluster_name)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Egress",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(envoy_cluster_upstream_cx_rx_bytes_total{envoy_cluster_name=~\"$envoy_cluster\"}[$__rate_interval])) by (envoy_cluster_name)",
       "legendFormat": "{{envoy_cluster_name}}"
      }
     ]
    },
    {
     "title": "Network: Transmit",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (pod) (rate(container_network_transmit_bytes_total{pod=~\"$pod\",namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network: Transmit errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (pod) (rate(container_network_transmit_errors_total{pod=~\"$pod\",namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network: Transmit packets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (pod) (rate(container_network_transmit_packets_total{pod=~\"$pod\",namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network: Dropped transmit packets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (pod) (rate(container_network_transmit_packets_dropped_total{pod=~\"$pod\",namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network: Receive",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (pod) (rate(container_network_receive_bytes_total{pod=~\"$pod\",namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network: Receive errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (pod) (rate(container_network_receive_errors_total{pod=~\"$pod\",namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network: Receive packets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (pod) (rate(container_network_receive_packets_total{pod=~\"$pod\",namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network: Dropped receive packets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (pod) (rate(container_network_receive_packets_dropped_total{pod=~\"$pod\",namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Process metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process Threads",
     "type": "timeseries",
     "description": "Number of used system threads",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "sum by(pod, container) (process_threads{cluster_id=\"$cluster_id\"})",
       "legendFormat": "Threads {{pod}}"
      }
     ]
    },
    {
     "title": "Process Major Page Faults",
     "type": "timeseries",
     "description": "Number of major page faults encountered by the process",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "targets": [
      {
       "expr": "sum by(pod) (process_major_page_faults_total{cluster_id=\"$cluster_id\"})",
       "legendFormat": "Major Faults {{pod}}"
      }
     ]
    },
    {
     "title": "Process Minor Page Faults",
     "type": "timeseries",
     "description": "Number of minor page faults encountered by the process",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "targets": [
      {
       "expr": "sum by(pod) (process_minor_page_faults_total{cluster_id=\"$cluster_id\"})",
       "legendFormat": "Minor Faults {{pod}}"
      }
     ]
    },
    {
     "title": "Process Open mmaps",
     "type": "timeseries",
     "description": "Number of open memory maps",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "sum by(pod) (process_open_mmaps{cluster_id=\"$cluster_id\"})",
       "legendFormat": "Memory Maps {{pod}}"
      }
     ]
    },
    {
     "title": "System Max mmaps",
     "type": "stat",
     "description": "System wide maximum number of open memory maps",
     "gridPos": { "h": 3, "w": 5, "x": 7, "y": 32 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(system_max_mmaps{cluster_id=\"$cluster_id\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Process Open fds",
     "type": "timeseries",
     "description": "Number of open file descriptors",
     "gridPos": { "h": 8, "w": 7, "x": 12, "y": 32 },
     "targets": [
      {
       "expr": "sum by(pod) (qdrant_process_open_fds{cluster_id=\"$cluster_id\"})",
       "legendFormat": "File Descriptors {{pod}}"
      }
     ]
    },
    {
     "title": "Process Max fds",
     "type": "stat",
     "description": "Maximum number of open file descriptors",
     "gridPos": { "h": 3, "w": 5, "x": 19, "y": 32 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(qdrant_process_max_fds{cluster_id=\"$cluster_id\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Usage mmaps",
     "type": "timeseries",
     "description": "Relation between process open memory maps and system wide maximum number of open memory maps",
     "gridPos": { "h": 5, "w": 5, "x": 7, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by(cluster_id) (process_open_mmaps{cluster_id=\"$cluster_id\"}) / (sum by(cluster_id) (system_max_mmaps{cluster_id=\"$cluster_id\"}))",
       "legendFormat": "Usage {{cluster_id}}"
      }
     ]
    },
    {
     "title": "Usage fds",
     "type": "timeseries",
     "description": "Relation between the number of open file descriptors and the maximum number of open file descriptors",
     "gridPos": { "h": 5, "w": 5, "x": 19, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by(cluster_id) (qdrant_process_open_fds{cluster_id=\"$cluster_id\"}) / (sum by(cluster_id) (qdrant_process_max_fds{cluster_id=\"$cluster_id\"}))",
       "legendFormat": "Usage {{cluster_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Snapshot metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Snapshot Creation Running",
     "type": "timeseries",
     "description": "Number of snapshots being created, per collection",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "sum by(cluster_id) (snapshot_creation_running{cluster_id=\"$cluster_id\"})",
       "legendFormat": "Snapshot Creation {{cluster_id}}"
      }
     ]
    },
    {
     "title": "Snapshot Recovery Running",
     "type": "timeseries",
     "description": "Number of snapshots being recovered, per collection",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 41 },
     "targets": [
      {
       "expr": "sum by(cluster_id) (snapshot_recovery_running{cluster_id=\"$cluster_id\"})",
       "legendFormat": "Snapshot Recovery {{cluster_id}}"
      }
     ]
    },
    {
     "title": "Snapshot Created Total",
     "type": "timeseries",
     "description": "Number of created snapshots since start, per collection",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 41 },
     "targets": [
      {
       "expr": "sum by(cluster_id) (snapshot_created_total{cluster_id=\"$cluster_id\"})",
       "legendFormat": "Total Snapshots {{cluster_id}}"
      }
     ]
    }
   ]
  }
 ]
}